DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS address;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE address (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY(user_id) REFERENCES user(id)
  address TEXT UNIQUE NOT NULL,
  username TEXT UNIQUE NOT NULL
);
